name: tmp_path
description: Generate a unique path in system temp directory.
version: 1.3.3
homepage: https://github.com/flutter-cavalry/tmp_path

environment:
  sdk: ">=2.18.2 <4.0.0"

dev_dependencies:
  mgenware_dart_lints: ^7.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.2
  uuid: ^4.1.0
